plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Selenium
    implementation 'org.seleniumhq.selenium:selenium-java:4.18.1'

    // TestNG
    implementation 'org.testng:testng:7.9.0'

    // REST Assured
    implementation 'io.rest-assured:rest-assured:5.4.0'

    // JSON Path
    implementation 'io.rest-assured:json-path:5.4.0'

    // WebDriverManager
    implementation 'io.github.bonigarcia:webdrivermanager:5.7.0'

    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'

    // Extent Reports
    implementation 'com.aventstack:extentreports:5.1.1'

    // Dotenv
    implementation 'io.github.cdimascio:dotenv-java:3.0.0'

    implementation 'commons-io:commons-io:2.15.1'
}

test {
    useTestNG() {
        suites "src/test/resources/testing.xml"
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}